Repository mimium-org/mimium-web, pull requests merged in 2021-01, with the labels that each got.

#12 Create Documentation “contributing”
  content/en/docs/contributing.en.md
  content/en/docs/contributing.ja.md
Labels: netlify-cms/pending_publish

#9 Create Getting-started “makingsound”
  content/en/docs/Getting started/makingsound.en.md
  content/en/docs/Getting started/makingsound.ja.md
Labels: netlify-cms/pending_review

#10 Update Documentation “_index”
  content/en/docs/_index.en.md
  content/en/docs/_index.ja.md
Labels: netlify-cms/pending_review

#11 Update Development “codingstyle”
  content/en/docs/Development/codingstyle.en.md
  content/en/docs/Development/codingstyle.ja.md
Labels: netlify-cms/draft

#15 Create Contributing “code-of-conduct”
  content/en/docs/Contributing/code-of-conduct.en.md
  content/en/docs/Contributing/code-of-conduct.ja.md
Labels: netlify-cms/pending_publish

#16 Create Contributing “contribution-guide”
  content/en/docs/Contributing/contribution-guide.en.md
  content/en/docs/Contributing/contribution-guide.ja.md
Labels: netlify-cms/pending_publish

#17 Create Contributing “documentation-guide”
  content/en/docs/Contributing/documentation-guide.en.md
  content/en/docs/Contributing/documentation-guide.ja.md
Labels: netlify-cms/pending_publish

#18 Create Contributing “community”
  content/en/docs/Contributing/community.en.md
  content/en/docs/Contributing/community.ja.md
Labels: netlify-cms/pending_publish

#19 Create Language-Specification “concept”
  content/en/docs/Users Guide/Language Specification/concept.en.md
  content/en/docs/Users Guide/Language Specification/concept.ja.md
Labels: netlify-cms/pending_publish

#20 Create Language-Specification “grammar-rule”
  content/en/docs/Users Guide/Language Specification/grammar-rule.en.md
  content/en/docs/Users Guide/Language Specification/grammar-rule.ja.md
Labels: netlify-cms/pending_publish

#21 Update Language-Specification “grammar-rule”
  content/en/docs/Users Guide/Language Specification/grammar-rule.en.md
  content/en/docs/Users Guide/Language Specification/grammar-rule.ja.md
Labels: netlify-cms/pending_publish

#22 Create Developers-Guide “structure-of-mimium”
  content/en/docs/Developers Guide/structure-of-mimium.en.md
  content/en/docs/Developers Guide/structure-of-mimium.ja.md
Labels: netlify-cms/pending_publish

#23 Create Developers-Guide “implementation”
  content/en/docs/Developers Guide/implementation.en.md
  content/en/docs/Developers Guide/implementation.ja.md
Labels: netlify-cms/pending_publish

#24 Update Developers-Guide “implementation”
  content/en/docs/Developers Guide/implementation.en.md
  content/en/docs/Developers Guide/implementation.ja.md
Labels: netlify-cms/pending_publish

#25 Create Developers-Guide “compiler”
  content/en/docs/Developers Guide/compiler.en.md
  content/en/docs/Developers Guide/compiler.ja.md
Labels: netlify-cms/pending_publish

#26 Create Developers-Guide “runtime”
  content/en/docs/Developers Guide/runtime.en.md
  content/en/docs/Developers Guide/runtime.ja.md
Labels: netlify-cms/pending_publish

#27 Create Developers-Guide “others”
  content/en/docs/Developers Guide/others.en.md
  content/en/docs/Developers Guide/others.ja.md
Labels: netlify-cms/pending_publish

#28 Create Developers-Guide “mimium-library-api-reference”
  content/en/docs/Developers Guide/mimium-library-api-reference.en.md
  content/en/docs/Developers Guide/mimium-library-api-reference.ja.md
Labels: netlify-cms/pending_publish

#29 Create Developers-Guide “c-design-pattern”
  content/en/docs/Developers Guide/c-design-pattern.en.md
  content/en/docs/Developers Guide/c-design-pattern.ja.md
Labels: netlify-cms/pending_publish

#30 Update Contributing “documentation-guide”
  content/en/docs/Contributing/documentation-guide.ja.md
Labels: netlify-cms/pending_publish

#31 Create Getting-started “examples”
  content/en/docs/Users Guide/Getting started/examples.en.md
  content/en/docs/Users Guide/Getting started/examples.ja.md
Labels: netlify-cms/pending_publish

#32 Create Language-Specification “built-in-function”
  content/en/docs/Users Guide/Language Specification/built-in-function.en.md
  content/en/docs/Users Guide/Language Specification/built-in-function.ja.md
Labels: netlify-cms/pending_publish

#33 Update Language-Specification “grammar-rule”
  content/en/docs/Users Guide/Language Specification/grammar-rule.en.md
  content/en/docs/Users Guide/Language Specification/grammar-rule.ja.md
Labels: netlify-cms/pending_publish

#34 Create Users-Guide “library”
  content/en/docs/Users Guide/library.en.md
  content/en/docs/Users Guide/library.ja.md
Labels: netlify-cms/pending_publish

#35 Update Contributing “code-of-conduct”
  content/en/docs/Contributing/code-of-conduct.en.md
  content/en/docs/Contributing/code-of-conduct.ja.md
Labels: netlify-cms/draft

#36 Update Contributing “code-of-conduct”
  content/en/docs/Contributing/code-of-conduct.en.md
  content/en/docs/Contributing/code-of-conduct.ja.md
Labels: netlify-cms/pending_publish
